/* eslint-disable no-unused-vars */
import { useState } from 'react';
import {FormField,Loader} from '../components'
import { useNavigate } from 'react-router-dom';
import { getRandomPrompt } from '../utils';
import { preview } from '../assets';


const handleSubmit =()=>{

}
const handleChange =(e)=>{

}
const handleSurpriseMe=()=>{
  
}
const CreatePost = () => {
  const navigate =useNavigate();
  const [form, setForm] = useState({
    name:'',
    prompt:'',
    photo:'',
  })
  const [generatingImg, setGeneratingImg] = useState(false)
  const [loading, setLoading] = useState(false)
  return (
   <section className='max-w-7xl mx-auto'>
        <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
            Create
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
       Create imaginative and visually stunning images generated by Pixal-Orbit AI and share them with the Community
        </p>
        </div>
        <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
        <FormField
        LableName ="Your Name"
        type="text"
        name='name'
        placeholder ='Adam Black'
        value ={form.name}
        handleChange={handleChange}
        />
            <FormField
        LableName ="prompt"
        type="text"
        name="prompt"
        placeholder ='T-Rex battling a dragon in an epic volcanic landscape, surrounded by fire and smoke'
        value ={form.prompt}
        handleChange={handleChange}
        isSurpriseMe
        handleSurpriseMe={handleSurpriseMe}
        />
        </div>
        </form>

   </section>
  )
}

export default CreatePost